### ISSUE TITLE
监听IPv6出错退出

### ISSUE THREAD

**Issue by Jerry-Y1** [lyswhut/lx-music-sync-server#55]
版本2.1.1

在配置文件中 设置BIND_IP为‘::’监听ipv6，软件链接服务器时出现下面报错后 退出

```
[2023-10-26T11:28:08.282] [INFO] startup - starting sync server in production
[2023-10-26T11:28:08.307] [INFO] startup - Listening on :: port 2233
new user data manage: user1
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at handleConnection (/root/Servers/lx-music/lx-music-sync-server/server/server/server.js:55:23)
    at WebSocketServer.<anonymous> (/root/Servers/lx-music/lx-music-sync-server/server/server/server.js:255:14)
    at WebSocketServer.emit (node:events:513:28)
    at done (/root/Servers/lx-music/lx-music-sync-server/server/server/server.js:269:22)
    at WebSocketServer.completeUpgrade (/root/Servers/lx-music/lx-music-sync-server/node_modules/ws/lib/websocket-server.js:427:5)
    at WebSocketServer.handleUpgrade (/root/Servers/lx-music/lx-music-sync-server/node_modules/ws/lib/websocket-server.js:336:10)
    at /root/Servers/lx-music/lx-music-sync-server/server/server/server.js:268:18
    at /root/Servers/lx-music/lx-music-sync-server/server/server/server.js:110:9 {
  input: '/socket?i=SaHm0HuIXE9jzsiTs8ccsA%3D%3D&t=pZPjUGkpM%2BkTIw2Pi6%2B28OaowAfXvDDHBi%2BdemvUyxQ%3D',
  code: 'ERR_INVALID_URL'
}
```

**Comment by lyswhut** [comment]
已在v2.1.2修复
