### ISSUE TITLE
用户密码为纯数字（例如12345678）的时候会报错退出

### ISSUE THREAD

**Issue by esme518** [lyswhut/lx-music-sync-server#6]
服务器版本为release下载的1.2.2
客户端为mac 2.2.0
```
> lx-music-sync-server@1.2.2 start
> node ./index.js

PORT: 9527
BIND_IP: 0.0.0.0
LX_USER_user1: 12345678
Load config: /server/config.js
[2023-03-26T19:47:33.263] [INFO] startup - starting sync server in production
[2023-03-26T19:47:33.270] [INFO] startup - Listening on 0.0.0.0 port 9527
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at Function.from (node:buffer:328:9)
    at authCode (/server/server/server/auth.js:51:58)
    at Server.<anonymous> (/server/server/server/server.js:153:42)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:998:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by esme518** [comment]
忘了写环境了 我是用docker运行 并使用环境变量LX_USER_设置user的时候这个问题的
多次测试后发现这个问题只有在**配置方式1简写模式**才会出现
配置方式2JSON字符串格式则没有这个问题

**Comment by lyswhut** [comment]
已在v1.2.3修复
