### ISSUE TITLE
认证报错

### ISSUE THREAD

**Issue by fanite** [lyswhut/lx-music-sync-server#60]
```log
Load env: 
  PORT: 9527
  BIND_IP: 0.0.0.0
  LOG_PATH: /server/data/logs
  DATA_PATH: /server/data/data
  LX_USER_os: os_0668
Load config: /server/config.js
Users:
  os: os_0668

[2024-02-04T13:30:22.460] [INFO] startup - starting sync server in production
[2024-02-04T13:30:22.468] [INFO] startup - Listening on 0.0.0.0 port 9527
Error: failed
    at authConnect (/server/server/server/auth.js:135:11)
    at authConnection (/server/server/server/server.js:109:28)
    at Server.upgrade (/server/server/server/server.js:260:9)
    at Server.emit (node:events:517:28)
    at onParserExecuteCommon (node:_http_server:915:14)
    at onParserExecute (node:_http_server:809:3)
```

部署环境：k8s

开始可以连接成功，但是马上就报Unexpected server respone:401

**Comment by fanite** [comment]
知道原因了，原来是livenessProbe访问时没有认证码，导致pod重启
